# Generated by Django 5.0.3 on 2024-04-07 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=20)),
                ('dni', models.CharField(help_text='Sin puntos', max_length=10, primary_key=True, serialize=False)),
                ('provincia', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('precio', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('electronica', 'electronica'), ('electrodomestico', 'electrodomestico'), ('ho', 'hogar'), ('de', 'deportes')], max_length=30)),
                ('stockActual', models.IntegerField(default=0)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miApp.proveedor')),
            ],
            options={
                'ordering': ['categoria', 'nombre'],
            },
        ),
    ]
