# Generated by Django 5.0.3 on 2024-04-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('electronica', 'electronica'), ('electrodomestico', 'electrodomestico'), ('hogar', 'hogar'), ('deporte', 'deportes')], max_length=30),
        ),
    ]
